@startuml

enum MovementInstructionType {
TURN_LEFT
TURN_RIGHT
FORWARD
BACKWARD
}

class MarsRoverMap {
    area
    obstacles
}


enum DirectionType{
    SOUTH
    NORTH
    EAST
    WEST
}

class MarsRover {
    currentDirection: DirectionType
    currentPosition: Coordinate
    map: MarsRoverMap
}

@enduml